version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'RABBITMQ'
    volumes:
       - ./data/rabbitmq/:/var/lib/rabbitmq/
       - ./data/enabled_plugins:/etc/rabbitmq/enabled_plugins
    expose:
       - 15672
       - 1883
    networks:
       - traefik
       - mqtt
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.${SERVICE.RABBITMQ}.entrypoints=http"
       - "traefik.http.routers.${SERVICE.RABBITMQ}.rule=Host(`${CONTAINERURL.RABBITMQ}`)"
       - "traefik.http.middlewares.${SERVICE.RABBITMQ}-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.${SERVICE.RABBITMQ}.middlewares=${SERVICE.RABBITMQ}-https-redirect"
       - "traefik.http.routers.${SERVICE.RABBITMQ}-secure.entrypoints=https"
       - "traefik.http.routers.${SERVICE.RABBITMQ}-secure.rule=Host(`${CONTAINERURL.RABBITMQ}`)"
       - "traefik.http.routers.${SERVICE.RABBITMQ}-secure.tls=true"
       - "traefik.docker.network=traefik"
       - "traefik.http.services.${SERVICE.RABBITMQ}.loadbalancer.server.port=3000"

       - "traefik.tcp.routers.${SERVICE.RABBITMQ}_mqtt.rule=HostSNI(`*`)"
       - "traefik.tcp.services.${SERVICE.RABBITMQ}_mqtt.loadbalancer.server.port=1883"
       - "traefik.tcp.routers.${SERVICE.RABBITMQ}_mqtt.entrypoints=mqtt"
       - "traefik.tcp.routers.${SERVICE.RABBITMQ}_mqtt.service=${SERVICE.RABBITMQ}_mqtt"
       
       - "flame.type=application"
       - "flame.name=RabbitMQ"
       - "flame.url=${CONTAINERURL.RABBITMQ}"
       - "flame.icon=protocol"

networks:
  traefik:
    external: true
  mqtt:
    external: true
