version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:${TAGRABBITMQ}
    container_name: ${CONTAINERNAMERABBITMQ}
    volumes:
       - ./data/rabbitmq/:/var/lib/rabbitmq/
       - ./data/enabled_plugins:/etc/rabbitmq/enabled_plugins
    expose:
       - 15672
       - 1883
    networks:
       - traefik
       - mqtt
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.${SERVICERABBITMQ}.entrypoints=http"
       - "traefik.http.routers.${SERVICERABBITMQ}.rule=Host(`${SERVICERABBITMQ}.${FQDN}`)"
       - "traefik.http.middlewares.${SERVICERABBITMQ}-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.${SERVICERABBITMQ}.middlewares=${SERVICERABBITMQ}-https-redirect"
       - "traefik.http.routers.${SERVICERABBITMQ}-secure.entrypoints=https"
       - "traefik.http.routers.${SERVICERABBITMQ}-secure.rule=Host(`${SERVICERABBITMQ}.${FQDN}`)"
       - "traefik.http.routers.${SERVICERABBITMQ}-secure.tls=true"
       - "traefik.docker.network=traefik"
       - "traefik.http.services.${SERVICERABBITMQ}.loadbalancer.server.port=3000"

       - "traefik.tcp.routers.${SERVICERABBITMQ}_mqtt.rule=HostSNI(`*`)"
       - "traefik.tcp.services.${SERVICERABBITMQ}_mqtt.loadbalancer.server.port=1883"
       - "traefik.tcp.routers.${SERVICERABBITMQ}_mqtt.entrypoints=mqtt"
       - "traefik.tcp.routers.${SERVICERABBITMQ}_mqtt.service=${SERVICERABBITMQ}_mqtt"
       
       - "flame.type=application"
       - "flame.name=RabbitMQ"
       - "flame.url=${SERVICERABBITMQ}.${FQDN}"
       - "flame.icon=protocol"

networks:
  traefik:
    external: true
  mqtt:
    external: true
