version: "3"

volumes:
  guacamole:

services:
  guacamole:
    container_name: "System-Guacamole"
    restart: always
    image: onzu/guacamole:{GUACAMOLE_TAG}
    ports:
      - 8181:8080
    volumes:
      - guacamole:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE}.entrypoints=http"
      - "traefik.http.routers.${SERVICE}.rule=Host(`remote.local.asuras.network`)"
      - "traefik.http.middlewares.${SERVICE}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE}.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.${SERVICE}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE}-secure.rule=Host(`remote.local.asuras.network`)"
      - "traefik.http.routers.${SERVICE}-secure.tls=true"
