version: "2.1"
services:
  papermerge:
    image: lscr.io/linuxserver/papermerge
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config/:/config
      - ./data/datadir/:/data
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE}.entrypoints=http"
      - "traefik.http.routers.${SERVICE}.rule=Host(`dms.local.asuras.network`)"
      - "traefik.http.middlewares.${SERVICE}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE}.middlewares=${SERVICE}-https-redirect"
      - "traefik.http.routers.${SERVICE}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE}-secure.rule=Host(`dms.local.asuras.network`)"
      - "traefik.http.routers.${SERVICE}-secure.tls=true"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
