version: '3.6'

services:
  flame:
    image: pawelmalak/flame:${TAGFLAME}
    container_name: ${CONTAINERNAMEFLAME}
    volumes:
      - ./data/app:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    secrets:
      - password # optional but required for (1)
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICEFLAME}.entrypoints=http"
      - "traefik.http.routers.${SERIVCEFLAME}.rule=Host(`${SERIVCEFLAME}.${FQDN}`)"
      - "traefik.http.middlewares.${SERIVCEFLAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERIVCEFLAME}.middlewares=${SERIVCEFLAME}-https-redirect"
      - "traefik.http.routers.${SERIVCEFLAME}-secure.entrypoints=https"
      - "traefik.http.routers.${SERIVCEFLAME}-secure.rule=Host(`${SERIVCEFLAME}.${FQDN}`)"
      - "traefik.http.routers.${SERIVCEFLAME}-secure.tls=true"
      - "traefik.docker.network=traefik"
    environment:
      - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
    restart: unless-stopped

# optional but required for Docker secrets (1)
secrets:
  password:
    file: ./data/secrets/password

networks:
  traefik:
    external: true
