version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:${TAG.SYNCTHING}
    container_name: ${CONTAINER_NAME.SYNCTHING}
    env_file:
      - ../.env
      - .env-overwrite
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config:/config
      - ./data/data1:/data1
      - ./data/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE.SYNCTHING}.entrypoints=http"
      - "traefik.http.routers.${SERVICE.SYNCTHING}.rule=Host(`${SERVICE.SYNCTHING}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICE.SYNCTHING}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE.SYNCTHING}.middlewares=${SERVICE.SYNCTHING}-https-redirect"
      - "traefik.http.routers.${SERVICE.SYNCTHING}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE.SYNCTHING}-secure.rule=Host(`${SERVICE.SYNCTHING}.${FQDN}`)"
      - "traefik.http.routers.${SERVICE.SYNCTHING}-secure.tls=true"
      - "traefik.http.services.${SERVICE.SYNCTHING}.loadbalancer.server.port=8384"
      - "flame.type=application"
      - "flame.name=Syncthing"
      - "flame.url=${SERVICE.SYNCTHING}.${FQDN}"
      - "flame.icon=cloud-sync-outline"
networks:
  traefik:
    external: true
