version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config:/config
      - ./data/data1:/data1
      - ./data/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - traefik
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${SERVICE}.entrypoints=http"
          - "traefik.http.routers.${SERVICE}.rule=Host(`${CONTAINERURL}`)"
          - "traefik.http.middlewares.${SERVICE}-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.${SERVICE}.middlewares=${SERVICE}-https-redirect"
          - "traefik.http.routers.${SERVICE}-secure.entrypoints=https"
          - "traefik.http.routers.${SERVICE}-secure.rule=Host(`${CONTAINERURL}`)"
          - "traefik.http.routers.${SERVICE}-secure.tls=true"
          - "traefik.http.services.${SERVICE}.loadbalancer.server.port=8384"
networks:
  traefik:
    external: true
