version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:${TAGSYNCTHING}
    container_name: ${CONTAINERNAMESYNCTHING}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config:/config
      - ./data/data1:/data1
      - ./data/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICESYNCTHING}.entrypoints=http"
      - "traefik.http.routers.${SERVICESYNCTHING}.rule=Host(`${SERVICESYNCTHING}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICESYNCTHING}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICESYNCTHING}.middlewares=${SERVICESYNCTHING}-https-redirect"
      - "traefik.http.routers.${SERVICESYNCTHING}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICESYNCTHING}-secure.rule=Host(`${SERVICESYNCTHING}.${FQDN}`)"
      - "traefik.http.routers.${SERVICESYNCTHING}-secure.tls=true"
      - "traefik.http.services.${SERVICESYNCTHING}.loadbalancer.server.port=8384"
      - "flame.type=application"
      - "flame.name=Syncthing"
      - "flame.url=${SERVICESYNCTHING}.${FQDN}"
      - "flame.icon=cloud-sync-outline"
networks:
  traefik:
    external: true
