version: '3.6'

services:
  dbeaver:
    image: dbeaver/cloudbeaver:${TAGCLOUDBEAVER}
    container_name: ${CONTAINERNAMECLOUDBEAVER}
    volumes:
      - dbeaver:/opt/cloudbeaver/workspace
    ports:
      - 81:8978
    networks:
      - traefik
      - database_bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICECLOUDBEAVER}.entrypoints=http"
      - "traefik.http.routers.${SERVICECLOUDBEAVER}.rule=Host(`${SERVICECLOUDBEAVER}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICECLOUDBEAVER}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICECLOUDBEAVER}.middlewares=${SERVICECLOUDBEAVER}-https-redirect"
      - "traefik.http.routers.${SERVICECLOUDBEAVER}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICECLOUDBEAVER}-secure.rule=Host(`${SERVICECLOUDBEAVER}.${FQDN}`)"
      - "traefik.http.routers.${SERVICECLOUDBEAVER}-secure.tls=true"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=DBeaver"
      - "flame.url=${SERVICECLOUDBEAVER}.${FQDN}"
      - "flame.icon=database"
    restart: unless-stopped

volumes:
  dbeaver:
    driver: local
    
networks:
  traefik:
    external: true
  database_bridge:
    external: true
