version: "3"
services:
    vaultwarden:
        image: vaultwarden/server:${TAGVAULTWARDEN}
        container_name: ${CONTAINERNAMEVAULTWARDEN}
        ports:
         - 81:80
        networks:
         - traefik
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${SERVICEVAULTWARDEN}.entrypoints=http"
          - "traefik.http.routers.${SERVICEVAULTWARDEN}.rule=Host(`${SERVICEVAULTWARDEN}.${FQDN}`)"
          - "traefik.http.middlewares.${SERVICEVAULTWARDEN}-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.${SERVICEVAULTWARDEN}.middlewares=${SERVICEVAULTWARDEN}-https-redirect"
          - "traefik.http.routers.${SERVICEVAULTWARDEN}-secure.entrypoints=https"
          - "traefik.http.routers.${SERVICEVAULTWARDEN}-secure.rule=Host(`${SERVICEVAULTWARDEN}.${FQDN}`)"
          - "traefik.http.routers.${SERVICEVAULTWARDEN}-secure.tls=true"
          - "flame.type=application"
          - "flame.name=Vaultwarden"
          - "flame.url=${SERVICEVAULTWARDEN}.${FQDN}"
          - "flame.icon=safe-square-outline"
        volumes:
          - ./data/:/data/
networks:
    traefik:
        external: true
