version: "3"
services:
    vaultwarden:
        image: vaultwarden/server:${VAULTWARDEN_TAG}
        container_name: Vaultwarden
        ports:
         - 81:80
        networks:
         - traefik
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${SERVICE}.entrypoints=http"
          - "traefik.http.routers.${SERVICE}.rule=Host(`${CONTAINERURL}`)"
          - "traefik.http.middlewares.${SERVICE}-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.${SERVICE}.middlewares=${SERVICE}-https-redirect"
          - "traefik.http.routers.${SERVICE}-secure.entrypoints=https"
          - "traefik.http.routers.${SERVICE}-secure.rule=Host(`${CONTAINERURL}`)"
          - "traefik.http.routers.${SERVICE}-secure.tls=true"
          - "flame.type=application"
          - "flame.name=Vaultwarden"
          - "flame.url=${CONTAINERURL}"
          - "flame.icon=safe-square-outline"
        volumes:
          - ./data/:/data/
networks:
    traefik:
        external: true
