version: '3'

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    env_file:
      - ../.env
      - .env-overwrite
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./data/upload:/home/${USER.FTP}/upload"
    environment:
      PUBLICHOST: "${HOST.FTP}"
      FTP_USER_NAME: ${USER.FTP}
      FTP_USER_PASS: ${PASS.FTP}
      FTP_USER_HOME: ${HOME.FTP}
      FTP_USER_UID: ${UID.FTP}
      FTP_USER_GID: ${GID.FTP}
    restart: always
