version: '2'
services:
    postgres:
      image: postgres:${TAGPOSTGRESGOGS}
      restart: always
      container_name: ${CONTAINERNAMEPOSTGRESGOGS}
      env_file:
       - ../.env
       - .env-overwrite
      environment:
       - "POSTGRES_USER=${USERPOSTGRESGOGS}"
       - "POSTGRES_PASSWORD=${PASSWORDPOSTGRESGOGS}"
       - "POSTGRES_DB=gogs"
      volumes:
       - "db-data:/var/lib/postgresql/data"
      networks:
       - gogs
       - database_bridge
    gogs:
      image: gogs/gogs:${TAGGOGS}
      restart: always
      container_name: ${CONTAINERNAMEGOGS}
      env_file:
       - ../.env
       - .env-overwrite
      ports:
       - "10022:22"
       - "3000:3000"
      links:
       - postgres
      environment:
       - "RUN_CROND=true"
      networks:
       - traefik
       - gogs
      volumes:
       - "gogs-data:/data"
      labels:
       - "traefik.enable=true"
       - "traefik.http.routers.${SERVICEGOGS}.entrypoints=http"
       - "traefik.http.routers.${SERVICEGOGS}.rule=Host(`${SERVICEGOGS}.${FQDN}`)"
       - "traefik.http.middlewares.${SERVICEGOGS}-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.${SERVICEGOGS}.middlewares=${SERVICE.GOGS}-https-redirect"
       - "traefik.http.routers.${SERVICEGOGS}-secure.entrypoints=https"
       - "traefik.http.routers.${SERVICEGOGS}-secure.rule=Host(`${SERVICEGOGS}.${FQDN}`)"
       - "traefik.http.routers.${SERVICEGOGS}-secure.tls=true"
       - "traefik.docker.network=traefik"
       - "traefik.http.services.${SERVICEGOGS}.loadbalancer.server.port=3000"
       - "flame.type=application"
       - "flame.name=Git"
       - "flame.url=${SERVICEGOGS}.${FQDN}"
       - "flame.icon=git"
      depends_on:
       - postgres

networks:
    traefik:
      external: true
    database_bridge:
      external: true
    gogs:
      driver: bridge

volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local
