version: '2'
services:
    postgres:
      image: postgres:9.5
      restart: always
      container_name: GOGS_DB
      env_file:
       - ../.env
       - .env-overwrite
      environment:
       - "POSTGRES_USER=${USER.POSTGRES.GOGS}"
       - "POSTGRES_PASSWORD=${PASSWORD.POSTGRES.GOGS}"
       - "POSTGRES_DB=gogs"
      volumes:
       - "db-data:/var/lib/postgresql/data"
      networks:
       - gogs
       - database_bridge
    gogs:
      image: gogs/gogs:${VERSION.GOGS}
      restart: always
      container_name: GOGS
      env_file:
       - ../.env
       - .env-overwrite
      ports:
       - "10022:22"
       - "3000:3000"
      links:
       - postgres
      environment:
       - "RUN_CROND=true"
      networks:
       - traefik
       - gogs
      volumes:
       - "gogs-data:/data"
      labels:
       - "traefik.enable=true"
       - "traefik.http.routers.${SERVICE.GOGS}.entrypoints=http"
       - "traefik.http.routers.${SERVICE}.rule=Host(`${CONTAINERURL.GOGS}`)"
       - "traefik.http.middlewares.${SERVICE.GOGS}-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.${SERVICE.GOGS}.middlewares=${SERVICE.GOGS}-https-redirect"
       - "traefik.http.routers.${SERVICE.GOGS}-secure.entrypoints=https"
       - "traefik.http.routers.${SERVICE.GOGS}-secure.rule=Host(`${CONTAINERURL.GOGS}`)"
       - "traefik.http.routers.${SERVICE.GOGS}-secure.tls=true"
       - "traefik.docker.network=traefik"
       - "traefik.http.services.${SERVICE.GOGS}.loadbalancer.server.port=3000"
       - "flame.type=application"
       - "flame.name=Git"
       - "flame.url=${CONTAINERURL.GOGS}"
       - "flame.icon=git"
      depends_on:
       - postgres

networks:
    traefik:
      external: true
    database_bridge:
      external: true
    gogs:
      driver: bridge

volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local
