version: '3.1'

services:

  postgres:
    image: postgres:11
    container_name: n8n_db
    env_file:
      - ../.env
      - .env-overwrite
    restart: always
    environment:
      - POSTGRES_USER=${USER.POSTRGES.N8N}
      - POSTGRES_PASSWORD=${PASSWORD.POSTGRES.N8N}
      - POSTGRES_DB=${DB.POSTGRES.N8N}
      - POSTGRES_NON_ROOT_USER=${NONROOT_USER.POSTGRES.N8N}
      - POSTGRES_NON_ROOT_PASSWORD=${NONROOT_PASSWORD.POSTGRES.N8N}
    volumes:
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    networks:
      - n8n_bridge

  n8n:
    image: n8nio/n8n
    container_name: n8n
    env_file:
      - ../.env
      - .env-overwrite
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${DB.POSTGRES.N8N}
      - DB_POSTGRESDB_USER=${NONROOT_USER.POSTGRES.N8N}
      - DB_POSTGRESDB_PASSWORD=${NONROOT_PASSWORD.POSTGRES.N8N}
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - ./data/n8n/:/home/node/.n8n
    networks:
      - traefik
      - n8n_bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE.N8N}.entrypoints=http"
      - "traefik.http.routers.${SERVICE.N8N}.rule=Host(`${CONTAINERURL.N8N}`)"
      - "traefik.http.middlewares.${SERVICE.N8N}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE.N8N}.middlewares=${SERVICE.N8N}-https-redirect"
      - "traefik.http.routers.${SERVICE.N8N}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE.N8N}-secure.rule=Host(`${CONTAINERURL.N8N}`)"
      - "traefik.http.routers.${SERVICE.N8N}-secure.tls=true"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=N8N"
      - "flame.url=${CONTAINERURL.N8N}"
      - "flame.icon=home-automation"
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"

networks:
  traefik:
    external: true
  n8n_bridge:
    driver: bridge
