version: "3"
services:
  traefik:
    image: traefik:${TAGTRAEFIK}
    container_name: ${CONTAINERNAMETRAEFIK}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      # RabbitMQ MQTT
      - 1883:1883
    environment:
      - CF_API_EMAIL=${CLOUDFLAREMAILTRAEFIK}
      - CF_DNS_API_TOKEN=${CLOUDFLARETOKENTRAEFIK}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICETRAEFIK}.entrypoints=http"
      - "traefik.http.routers.${SERVICETRAEFIK}.rule=Host(`${SERVICETRAEFIK}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICETRAEFIK}-auth.basicauth.users=${TRAEFIKUSER}:${TRAEFIKPASSWORD}"
      - "traefik.http.middlewares.${SERVICETRAEFIK}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.${SERVICETRAEFIK}.middlewares=traefik-https-redirect"
      - "traefik.http.routers.${SERVICETRAEFIK}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICETRAEFIK}-secure.rule=Host(`${SERVICETRAEFIK}.${FQDN}`)"
      - "traefik.http.routers.${SERVICETRAEFIK}-secure.middlewares=traefik-auth"
      - "traefik.http.routers.${SERVICETRAEFIK}-secure.tls=true"
      
      # Comment this Block for other Certresolver
      - "traefik.http.routers.${SERVICETRAEFIK}-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.${SERVICETRAEFIK}-secure.tls.domains[0].main=${FQDN}"
      - "traefik.http.routers.${SERVICETRAEFIK}-secure.tls.domains[0].sans=*.${FQDN}"
      - "traefik.http.routers.${SERVICETRAEFIK}-secure.service=api@internal"
      
      # Comment this Block out for other Certresolver
      #- "traefik.http.routers.traefik-secure.tls=true"
      #- "traefik.http.routers.traefik-secure.tls.certresolver=http"
      #- "traefik.http.routers.traefik-secure.service=api@internal"
      
      - "flame.type=application"
      - "flame.name=Traefik"
      - "flame.url=${SERVICETRAEFIK}.${FQDN}"
      - "flame.icon=traffic-light"

networks:
  traefik:
    external: true
