version: "3"
services:
  traefik:
    image: traefik:${TRAEFIK_TAG}
    container_name: TRAEFIK
    env_file:
      - ../.env
      - .env-overwrite
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      # RabbitMQ MQTT
      - 1883:1883
    environment:
      - CF_API_EMAIL=${CLOUDFLAREMAIL}
      - CF_DNS_API_TOKEN=${CLOUDFLARETOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE}.entrypoints=http"
      - "traefik.http.routers.${SERVICE}.rule=Host(`${CONTAINERURL}`)"
      - "traefik.http.middlewares.${SERVICE}-auth.basicauth.users=${DASHBOARDUSER}:${DASHBOARDPASS}"
      - "traefik.http.middlewares.${SERVICE}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.${SERVICE}.middlewares=traefik-https-redirect"
      - "traefik.http.routers.${SERVICE}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE}-secure.rule=Host(`${CONTAINERURL}`)"
      - "traefik.http.routers.${SERVICE}-secure.middlewares=traefik-auth"
      - "traefik.http.routers.${SERVICE}-secure.tls=true"
      - "traefik.http.routers.${SERVICE}-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.${SERVICE}-secure.tls.domains[0].main=local.asuras.network"
      - "traefik.http.routers.${SERVICE}-secure.tls.domains[0].sans=*.local.asuras.network"
      - "traefik.http.routers.${SERVICE}-secure.service=api@internal"
      - "flame.type=application"
      - "flame.name=Traefik"
      - "flame.url=${CONTAINERURL}"
      - "flame.icon=traffic-light"

networks:
  traefik:
    external: true
