version: "3.7"

services:
  node-red:
    image: nodered/node-red:${TAG.NODERED}
    container_name: NODE-RED
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    networks:
      - traefik
    volumes:
      - node-red-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICENODERED}.entrypoints=http"
      - "traefik.http.routers.${SERVICENODERED}.rule=Host(`${SERVICENODERED}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICENODERED}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICENODERED}.middlewares=${SERVICENODERED}-https-redirect"
      - "traefik.http.routers.${SERVICENODERED}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICENODERED}-secure.rule=Host(`${SERVICENODERED}.${FQDN}`)"
      - "traefik.http.routers.${SERVICENODERED}-secure.tls=true"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=NodeRed"
      - "flame.url=${SERVICENODERED}.${FQDN}"
      - "flame.icon=format-text-wrapping-overflow"

volumes:
  node-red-data:

networks:
  traefik:
    external: true
