version: '2.1'

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:${TAG.NEXTCLOUD}
    container_name: ${CONTAINER_NAME.NEXTCLOUD}
    env_file:
      - ../.env
      - .env-overwrite
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config/:/config
      - ${DATADIR.NEXTCLOUD}:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${SERVICE.NEXTCLOUD}.entrypoints=http"
      - "traefik.http.routers.${SERVICE.NEXTCLOUD}.rule=Host(`${SERVICE.NEXTCLOUD}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICE.NEXTCLOUD}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE.NEXTCLOUD}.middlewares=${SERVICE.NEXTCLOUD}-https-redirect"
      - "traefik.http.routers.${SERVICE.NEXTCLOUD}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE.NEXTCLOUD}-secure.rule=Host(`${SERVICE.NEXTCLOUD}.${FQDN}`)"
      - "traefik.http.routers.${SERVICE.NEXTCLOUD}-secure.tls=true"
      - "traefik.http.services.${SERVICE.NEXTCLOUD}.loadBalancer.server.port=443"
      - "traefik.http.services.${SERVICE.NEXTCLOUD}.loadBalancer.server.scheme=https"
      - "flame.type=application"
      - "flame.name=Nextcloud"
      - "flame.url=${SERVICE.NEXTCLOUD}.${FQDN}"
      - "flame.icon=cloud-download"
    restart: unless-stopped

networks:
  traefik:
    external: true
