version: '2.1'

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    env_file:
      - ../.env
      - .env-overwrite
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config/:/config
      - ./data/files/:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${SERVICE}.entrypoints=http"
      - "traefik.http.routers.${SERVICE}.rule=Host(`${CONTAINERURL}`)"
      - "traefik.http.middlewares.${SERVICE}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE}.middlewares=${SERVICE}-https-redirect"
      - "traefik.http.routers.${SERVICE}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE}-secure.rule=Host(`${CONTAINERURL}`)"
      - "traefik.http.routers.${SERVICE}-secure.tls=true"
      - "traefik.http.services.nextcloud.loadBalancer.server.port=443"
      - "traefik.http.services.nextcloud.loadBalancer.server.scheme=https"
    restart: unless-stopped

networks:
  traefik:
    external: true
