version: '2.1'

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:${TAGNEXTCLOUD}
    container_name: ${CONTAINERNAMENEXTCLOUD}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config/:/config
      - ${DATADIRNEXTCLOUD}:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${SERVICENEXTCLOUD}.entrypoints=http"
      - "traefik.http.routers.${SERVICENEXTCLOUD}.rule=Host(`${SERVICENEXTCLOUD}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICENEXTCLOUD}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICENEXTCLOUD}.middlewares=${SERVICENEXTCLOUD}-https-redirect"
      - "traefik.http.routers.${SERVICENEXTCLOUD}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICENEXTCLOUD}-secure.rule=Host(`${SERVICENEXTCLOUD}.${FQDN}`)"
      - "traefik.http.routers.${SERVICENEXTCLOUD}-secure.tls=true"
      - "traefik.http.services.${SERVICENEXTCLOUD}.loadBalancer.server.port=443"
      - "traefik.http.services.${SERVICENEXTCLOUD}.loadBalancer.server.scheme=https"
      - "flame.type=application"
      - "flame.name=Nextcloud"
      - "flame.url=${SERVICENEXTCLOUD}.${FQDN}"
      - "flame.icon=cloud-download"
    restart: unless-stopped

networks:
  traefik:
    external: true
