version: '3'
services:
  factorio:
    image: dtandersen/factorio:${TAGFACTORIO}
    container_name: ${CONTAINERNAMEFACTORIO}
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp" # Optional for RCON
    networks:
     - traefik
    volumes:
     - factorio:/factorio
    environment:
     - INSTANCE_NAME=Skullgames Factorio
     - INSTANCE_DESC=Ladida
    labels:
      - "flame.type=application"
      - "flame.name=Factorio"
      - "flame.url=${SERVICEFACTORIO}.${FQDN}"
      - "flame.icon=factory"

networks:
  traefik:
    external: true

volumes:
  factorio:
    driver: local
