version: '3'
services:
  factorio:
    image: dtandersen/factorio:${TAGFACTORIO}
    container_name: ${CONTAINERNAMEFACTORIO}
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp" # Optional for RCON
    networks:
     - traefik
    volumes:
     - factorio:/factorio
    environment:
     - INSTANCE_NAME=Skullgames Factorio
     - INSTANCE_DESC=Ladida
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICEFACTORIO}.entrypoints=http"
      - "traefik.http.routers.${SERVICEFACTORIO}.rule=Host(`${SERVICEFACTORIO}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICEFACTORIO}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICEFACTORIO}.middlewares=${SERVICEFACTORIO}-https-redirect"
      - "traefik.http.routers.${SERVICEFACTORIO}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICEFACTORIO}-secure.rule=Host(`${SERVICEFACTORIO}.${FQDN}`)"
      - "traefik.http.routers.${SERVICEFACTORIO}-secure.tls=true"
      - "traefik.http.services.${SERVICEFACTORIO}.loadbalancer.server.port=34197"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=Factorio"
      - "flame.url=${SERVICEFACTORIO}.${FQDN}"
      - "flame.icon=factory"

networks:
  traefik:
    external: true

volumes:
  factorio:
    driver: local
