version: '3.6'

services:
  dbeaver:
    image: dbeaver/cloudbeaver:${VERSION.CLOUDBEAVER}
    container_name: DBEAVER
    env_file:
      - ../.env
      - .env-overwrite
    volumes:
      - dbeaver:/opt/cloudbeaver/workspace
    ports:
      - 81:8978
    networks:
      - traefik
      - database_bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE.CLOUDBEAVER}.entrypoints=http"
      - "traefik.http.routers.${SERVICE.CLOUDBEAVER}.rule=Host(`${CONTAINERURL.CLOUDBEAVER}`)"
      - "traefik.http.middlewares.${SERVICE.CLOUDBEAVER}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE.CLOUDBEAVER}.middlewares=${SERVICE.CLOUDBEAVER}-https-redirect"
      - "traefik.http.routers.${SERVICE.CLOUDBEAVER}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE.CLOUDBEAVER}-secure.rule=Host(`${CONTAINERURL.CLOUDBEAVER}`)"
      - "traefik.http.routers.${SERVICE.CLOUDBEAVER}-secure.tls=true"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=DBeaver"
      - "flame.url=${CONTAINERURL.CLOUDBEAVER}"
      - "flame.icon=database"
    restart: unless-stopped

volumes:
  dbeaver:
    driver: local
    
networks:
  traefik:
    external: true
  database_bridge:
    external: true
