version: '3'

services:
  portainer:
    image: portainer/portainer-ce:${TAGPORTAINER}
    container_name: ${CONTAINERNAMEPORTAINER}
    env_file:
      - ../.env
      - .env-overwrite
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICEPORTAINER}.entrypoints=http"
      - "traefik.http.routers.${SERVICEPORTAINER}.rule=Host(`${SERVICEPORTAINER}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICEPORTAINER}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICEPORTAINER}.middlewares=${SERVICEPORTAINER}-https-redirect"
      - "traefik.http.routers.${SERVICEPORTAINER}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICEPORTAINER}-secure.rule=Host(`${SERVICEPORTAINER}.${FQDN}`)"
      - "traefik.http.routers.${SERVICEPORTAINER}-secure.tls=true"
      - "traefik.http.routers.${SERVICEPORTAINER}-secure.service=portainer"
      - "traefik.http.services.${SERVICEPORTAINER}.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=Portainer"
      - "flame.url=${SERVICEPORTAINER}.${FQDN}"
      - "flame.icon=docker"

networks:
  traefik:
    external: true
