version: '3'

services:
  portainer:
    image: portainer/portainer-ce:${TAG.PORTAINER}
    container_name: ${CONTAINER_NAME.PORTAINER}
    env_file:
      - ../.env
      - .env-overwrite
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE.PORTAINER}.entrypoints=http"
      - "traefik.http.routers.${SERVICE.PORTAINER}.rule=Host(`${SERVICE.PORTAINER}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICE.PORTAINER}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE.PORTAINER}.middlewares=${SERVICE.PORTAINER}-https-redirect"
      - "traefik.http.routers.${SERVICE.PORTAINER}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE.PORTAINER}-secure.rule=Host(`${SERVICE.PORTAINER}.${FQDN}`)"
      - "traefik.http.routers.${SERVICE.PORTAINER}-secure.tls=true"
      - "traefik.http.routers.${SERVICE.PORTAINER}-secure.service=portainer"
      - "traefik.http.services.${SERVICE.PORTAINER}.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=Portainer"
      - "flame.url=${SERVICE.PORTAINER}.${FQDN}"
      - "flame.icon=docker"

networks:
  traefik:
    external: true
