version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:${TAG.UPTIMEKUMA}
    container_name: ${CONTAINER_NAME.UPTIMEKUMA}
    env_file:
      - ../.env
      - .env-overwrite
    volumes:
      - ./data/uptime:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${SERVICE.UPTIMEKUMA}.entrypoints=http"
      - "traefik.http.routers.${SERVICE.UPTIMEKUMA}.rule=Host(`${SERVICE.UPTIMEKUMA}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICE.UPTIMEKUMA}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE.UPTIMEKUMA}.middlewares=${SERVICE.UPTIMEKUMA}-https-redirect"
      - "traefik.http.routers.${SERVICE.UPTIMEKUMA}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE.UPTIMEKUMA}-secure.rule=Host(`${SERVICE.UPTIMEKUMA}.${FQDN}`)"
      - "traefik.http.routers.${SERVICE.UPTIMEKUMA}-secure.tls=true"
      - "flame.type=application"
      - "flame.name=Uptime-Kuma"
      - "flame.url=${SERVICE.UPTIMEKUMA}.${FQDN}"
      - "flame.icon=alarm-light-outline"

networks:
  traefik:
    external: true
