version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:${TAGUPTIMEKUMA}
    container_name: ${CONTAINERNAMEUPTIMEKUMA}
    volumes:
      - ./data/uptime:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${SERVICEUPTIMEKUMA}.entrypoints=http"
      - "traefik.http.routers.${SERVICEUPTIMEKUMA}.rule=Host(`${SERVICEUPTIMEKUMA}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICEUPTIMEKUMA}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICEUPTIMEKUMA}.middlewares=${SERVICEUPTIMEKUMA}-https-redirect"
      - "traefik.http.routers.${SERVICEUPTIMEKUMA}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICEUPTIMEKUMA}-secure.rule=Host(`${SERVICEUPTIMEKUMA}.${FQDN}`)"
      - "traefik.http.routers.${SERVICEUPTIMEKUMA}-secure.tls=true"
      - "flame.type=application"
      - "flame.name=Uptime-Kuma"
      - "flame.url=${SERVICEUPTIMEKUMA}.${FQDN}"
      - "flame.icon=alarm-light-outline"

networks:
  traefik:
    external: true
