version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:${TAGHOMEASSISTANT}"
    container_name: ${CONTAINERNAMEHOMEASSISTANT}
    volumes:
      - /data/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICEHOMEASSISTANT}.entrypoints=http"
      - "traefik.http.routers.${SERVICEHOMEASSISTANT}.rule=Host(`${SERVICEHOMEASSISTANT}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICEHOMEASSISTANT}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICEHOMEASSISTANT}.middlewares=${SERVICE}-https-redirect"
      - "traefik.http.routers.${SERVICEHOMEASSISTANT}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICEHOMEASSISTANT}-secure.rule=Host(`${SERVICEHOMEASSISTANT}.${FQDN}`)"
      - "traefik.http.routers.${SERVICEHOMEASSISTANT}-secure.tls=true"
      - "traefik.http.services.${SERVICEHOMEASSISTANT}.loadbalancer.server.port=8123"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=HomeAssistant"
      - "flame.url=${SERVICEHOMEASSISTANT}.${FQDN}"
      - "flame.icon=home-automation"
    networks:
      - traefik
    #network_mode: host

networks:
  traefik:
    external: true
