version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    env_file:
      - ../.env
      - .env-overwrite
    volumes:
      - /data/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE.HOMEASSISTANT}.entrypoints=http"
      - "traefik.http.routers.${SERVICE.HOMEASSISTANT}.rule=Host(`${CONTAINERURL.HOMEASSISTANT}`)"
      - "traefik.http.middlewares.${SERVICE.HOMEASSISTANT}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE.HOMEASSISTANT}.middlewares=${SERVICE}-https-redirect"
      - "traefik.http.routers.${SERVICE.HOMEASSISTANT}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE.HOMEASSISTANT}-secure.rule=Host(`${CONTAINERURL.HOMEASSISTANT}`)"
      - "traefik.http.routers.${SERVICE.HOMEASSISTANT}-secure.tls=true"
      - "traefik.http.services.${SERVICE.HOMEASSISTANT}.loadbalancer.server.port=8123"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=HomeAssistant"
      - "flame.url=${CONTAINERURL.HOMEASSISTANT}"
      - "flame.icon=home-automation"
    networks:
      - traefik
    #network_mode: host

networks:
  traefik:
    external: true
