
version: "3"
services:
  christmas-community:
    image: wingysam/christmas-community:${TAGWISHLIST}
    container_name: WISHLIST
    volumes:
      - ./data:/data
    ports:
      - 83:80
    environment:
      # Amazon Smile, set to 'false' to disable www.amazon.com links
      # turning into smile.amazon.com
      SMILE: 'true'
      # Table mode, set to 'false' to revert to box mode
      TABLE: 'true'
      # Single list mode
      # (for weddings, birthdays, etc. only the admin account's list is accessible)
      # Set to 'true' to enable
      SINGLE_LIST: 'false'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICEWISHLIST}.entrypoints=http"
      - "traefik.http.routers.${SERVICEWISHLIST}.rule=Host(`${SERVICEWISHLIST}.${FQDN}`)"
      - "traefik.http.middlewares.${SERVICEWISHLIST}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICEWISHLIST}.middlewares=${SERVICEWISHLIST}-https-redirect"
      - "traefik.http.routers.${SERVICEWISHLIST}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICEWISHLIST}-secure.rule=Host(`${SERVICEWISHLIST}.${FQDN}`)"
      - "traefik.http.routers.${SERVICEWISHLIST}-secure.tls=true"
      - "traefik.docker.network=traefik"
      - "flame.type=application"
      - "flame.name=Wishlist"
      - "flame.url=${SERVICEWISHLIST}.${FQDN}"
      - "flame.icon=playlist-edit"
    restart: always

networks:
  traefik:
    external: true
